### PR TITLE
added LE 9.0 Projects and Devices

### PR DESCRIPTION
**Pull request by sky42src**

### CODE REVIEW

**Comment by chewitt** [comment]
I'd ask that we relist entries in alphabetically/ascending order, and I suspect the script will need some changes to handle the suffix format of RK board devices (else you'll have multiple RK3399 entries and no idea which one is which).

**Comment by sky42src** [comment]
I can do alphabetically/ascending. And for Rockchip i was wondering about that too, but i would need a hint how to do that. Needs LE settings also to know about UBOOT suffix for RK3328/99?

**Comment by sky42src** [comment]
I was trying to start small with the devices.

**Comment by MilhouseVH** [comment]
For a device with both arm and aarch64 releases, do we need to differentiate in the description, for example `Odroid C2 (aarch64)` and `Odroid C2 (arm)` (or some such variation)?

**Pull request merged**
