### PR TITLE
Make compatible with stable release infra too

### PR DESCRIPTION
**Pull request by antonlacon**
This replaces removeprefix and removesuffix with self-defined lchop and rchop, respectively. They're features of python >=3.9.  This is intended to make the script compatible with python 3.8 (probably >= 3.6).

### CODE REVIEW

**Comment by antonlacon** [comment]
Added two commits: import sorting is a cleanup commit; changes involving subpath are a bugfix when the release files are not in a subdirectory:

The script attempted to remove the "${input_directory}/" from the dirpath to establish the subpath of the file, but when the file wasn't in a subdirectory, it did not have the trailing '/' in the dirpath, resulting in just outputting the path.  (The trailing '/' is actually removed during script's init for unknown reasons, but it's a bigger look into the 'why' this is being done and being this is otherwise working...)

**Comment by antonlacon** [comment]
Last commit hardcodes some values for the LE-format-1.0 image file used by the USB-SD Creator instead of adding another regex to parse the filename. I chose to hardcode as it should only ever be the one image. I chose the unix epoch for its timestamp because it won't be used for anything, and should raise an eyebrow if seen in the wild.

**Comment by antonlacon** [comment]
I've added commits that complete creating the json release entries as used for stable releases in addition to the nightly process.

Two quirks: one is for the fourth version number as used in 8.2.5.1. This is broad and should handle other 4th version numbers if it comes up. The other is to not create uboot release entries for LE9 specifically, but to continue with the standard tar/img entries as the uboot images with a shared tarball was not in place at that time. These were otherwise being grouped together in interesting ways, such as for LibreELEC-RK3328.arm-8.90.015-box.tar, which also grabbed -box-trn9 and -box-z28 for uboot entries. The current release.json has the same problem.

Some cleanup commits in there too.

This is doing what I expect for releases.libreelec.tv and test.libreelec.tv. The USB-SD creator needs to be checked after deploy to make sure the additional fields don't cause an issue (no existing fields had their use/role/purpose changed), and that it wasn't relying on empty image release entries (these entries:
```
            "image": {
              "name": "",
              "sha256": "",
              "size": ""
            },
```

**Comment by CvH** [comment]
@antonlacon done ??

**Comment by antonlacon** [comment]
Looks good to me. USB-SD creator appears to be listing everything and downloaded an RPi2 image for me.

**Review by CvH — APPROVED** [review]

**Comment by antonlacon** [comment]
For future reference:

The USB-SD Creator can be tested with an alternative releases.json file by naming it `releases-user.json` and placing it in the same directory as the application prior to startup.

**Pull request merged**
